// This file was autogenerated by /usr/local/google-closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('main.js', ['app'], ['rokko.Map']);
goog.addDependency('map/Map.js', ['rokko.Map'], []);
goog.addDependency('rokko/components/Component.js', ['rokko.components.Component'], []);
goog.addDependency('rokko/components/GameLoopComponent.js', ['rokko.components.GameLoopComponent'], ['rokko.components.Component']);
goog.addDependency('rokko/components/MoveComponent.js', ['rokko.components.MoveComponent'], ['goog.events', 'rokko.components.Component']);
goog.addDependency('rokko/entities/Entity.js', ['rokko.entities.Entity'], ['rokko.components.Component', 'rokko.math.Vec2']);
goog.addDependency('rokko/factories/EntityFactory.js', ['rokko.factories.EntityFactory'], ['rokko.factories.SpriteFactory']);
goog.addDependency('rokko/factories/MapFactory.js', ['rokko.factories.MapFactory'], ['goog.dom', 'rokko.map.TileMap']);
goog.addDependency('rokko/factories/SpriteFactory.js', ['rokko.factories.SpriteFactory'], ['goog.net.XhrIo', 'rokko.graphics.SequencedImage', 'rokko.graphics.Sprite', 'rokko.math.Vec2']);
goog.addDependency('rokko/graphics/AnimatedSprite.js', ['rokko.graphics.AnimatedSprite'], ['rokko.graphics.Image', 'rokko.graphics.Sprite']);
goog.addDependency('rokko/graphics/Display.js', ['rokko.graphics.Display'], ['goog.dom']);
goog.addDependency('rokko/graphics/Image.js', ['rokko.graphics.Image'], ['goog.dom']);
goog.addDependency('rokko/graphics/Renderer.js', ['rokko.graphics.Renderer'], ['goog.dom']);
goog.addDependency('rokko/graphics/SequencedImage.js', ['rokko.graphics.SequencedImage'], ['rokko.graphics.Image']);
goog.addDependency('rokko/graphics/Sprite.js', ['rokko.graphics.Sprite'], ['rokko.graphics.Image']);
goog.addDependency('rokko/managers/EntityManager.js', ['rokko.managers.EntityManager'], []);
goog.addDependency('rokko/maps/TileMap.js', ['rokko.map.TileMap'], []);
goog.addDependency('rokko/math/Vec2.js', ['rokko.math.Vec2'], []);
