// This file was autogenerated by /usr/local/google-closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../demo/src/rokko/demo/components/Component.js', ['rokko.demo.components.Component'], []);
goog.addDependency('../../../../demo/src/rokko/demo/components/DrawComponent.js', ['rokko.demo.components.DrawComponent'], ['goog.dom', 'rokko.demo.components.Component']);
goog.addDependency('../../../../demo/src/rokko/demo/components/RendererComponent.js', ['rokko.demo.components.RendererComponent'], ['rokko.demo.components.Component']);
goog.addDependency('../../../../demo/src/rokko/demo/entities/Entity.js', ['rokko.demo.entities.Entity'], []);
goog.addDependency('../../../../demo/src/rokko/demo/graphics/Image.js', ['rokko.demo.graphics.Image'], ['goog.dom']);
