// This file was autogenerated by /usr/local/google-closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../demo/src/rokko/components/Component.js', ['rokko.components.Component'], []);
goog.addDependency('../../../../demo/src/rokko/components/DrawComponent.js', ['rokko.components.DrawComponent'], ['goog.dom', 'rokko.components.Component']);
goog.addDependency('../../../../demo/src/rokko/components/RendererComponent.js', ['rokko.components.RendererComponent'], ['rokko.components.Component']);
goog.addDependency('../../../../demo/src/rokko/entities/Entity.js', ['rokko.entities.Entity'], []);
goog.addDependency('../../../../demo/src/rokko/graphics/Image.js', ['rokko.graphics.Image'], []);
